services:

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: unless-stopped    
    user: 1000:1000 # adjust to your needs
    environment:
      - FB_BASEURL=/filebrowser    
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/filebrowser/data:/data
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/filebrowser/config:/config
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=proxy
    #  - traefik.http.routers.filebrowser.rule=Host(`filebrowser.example.com`)
    #  - traefik.http.services.filebrowser.loadbalancer.server.port=8080
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.filebrowser.middlewares=local-ipwhitelist@file

#networks:
#  proxy:
#    external: true      
